import numpy as np
import pandas as pd

df=pd.read_csv('ds3.csv')
df.replace(['?','--'],np.nan,inplace=True)
df.dropna(subset=['Car_ID'],inplace=True,axis=0)
df.dropna(subset=['Price (USD)'],inplace=True,axis=0)
df['Brand'].value_counts().idxmax()
df['Brand'].replace(np.nan,'Nissan',inplace=True)
df['Model_Type'].value_counts()
df['Model_Type'].replace(np.nan,'SUV',inplace=True)
df['Fuel_Type'].value_counts()
df['Fuel_Type'].replace(np.nan,'Petrol',inplace=True)
df['Transmission'].value_counts()
df['Transmission'].replace(np.nan,'Manual',inplace=True)
df['Region'].value_counts()
df['Region'].replace(np.nan,'Asia',inplace=True)
avg=df['Engine_Size (L)'].astype(float).mean()
df['Engine_Size (L)'].replace(np.nan,avg,inplace=True)
df['Engine_Size (L)'].replace(np.nan,avg1,inplace=True)
avg2=df['Torque (Nm)'].astype(int).mean()
df['Torque (Nm)'].replace(np.nan,avg2,inplace=True)
avg3=df['Weight (kg)'].astype(float).mean()
df['Weight (kg)'].replace(np.nan,avg3,inplace=True)
avg8=df['Resale_Value (USD)'].astype(float).mean()
df['Resale_Value (USD)'].replace(np.nan,avg8,inplace=True)
#df.dropna(subset=['Resale_Value (USD)'],inplace=True,axis=0).............
df.reset_index(drop=True,inplace=True)
avg1=df['Horsepower (hp)'].astype(float).mean()
df['Horsepower (hp)'].replace(np.nan,avg1,inplace=True)
avg4=df['Fuel_Economy (km/l)'].astype(float).mean()
df['Fuel_Economy (km/l)'].replace(np.nan,avg4,inplace=True)
df['Seating_Capacity'].value_counts()
df['Seating_Capacity'].replace(np.nan,2.0,inplace=True)
df.dropna(subset=['Service_Cost (USD/Year)'],inplace=True,axis=0)
#Safety_Rating
df['Safety_Rating'].value_counts()
df['Safety_Rating'].replace(np.nan,2,inplace=True)
avg5=df['Ground_Clearance (mm)'].astype(float).mean()
df['Safety_Rating'].replace(np.nan,avg5,inplace=True)
df['Warranty (Years)'].value_counts()
df['Safety_Rating'].replace(np.nan,5,inplace=True)
avg6=df['Wheelbase (mm)'].astype(float).mean()
df['Wheelbase (mm)'].replace(np.nan,avg6,inplace=True)
avg7=df['Boot_Space (L)'].astype(float).mean()
df['Boot_Space (L)'].replace(np.nan,avg7,inplace=True)

duplicates=df[df.duplicated()]
df.drop_duplicates(inplace=True)
df.reset_index(drop=True,inplace=True)
df.info()
df.head(60)


